# SELECT Command Algorithm in Hypercode
# Version: 1.1.0
# Purpose: Select next task from workplan based on priorities and dependencies

"SELECT — Next Task Selection"
    "Version: 1.1.0"

    "Purpose"
        "SELECT identifies the next task to work on based on priorities, dependencies, and critical path."
        "It does NOT create implementation plans - that's the job of the PLAN command."

    "Inputs"
        "DOCS/Workplan.md"
            "Contains all project tasks with priorities and dependencies"
        "DOCS/INPROGRESS/next.md"
            "Current task being worked on"

    "Algorithm"
        "Step 1: Find Candidate Tasks"
            "Filter tasks by status"
                "Task must not be completed (checkbox is [ ] not [x])"
            "Check dependencies"
                "All dependent tasks must be completed"
                "Read Dependencies field from task definition"
                "Verify each dependency is marked [x] in Workplan"
            "Apply priority ordering"
                "P0 tasks have highest priority"
                "P1 tasks have medium priority"
                "P2 tasks have lowest priority"
            "Break ties"
                "If multiple tasks same priority, prefer critical path"
                "If still tied, use sequential task order"

        "Step 2: Create Minimal next.md"
            "Write task header"
                "Format: # Next Task: {TASK_ID} — {TASK_NAME}"
            "Add basic metadata"
                "Priority: P0/P1/P2"
                "Phase: {Phase Name}"
                "Effort: {Hours}"
                "Dependencies: {Task IDs or None}"
                "Status: Selected"
            "Add brief description"
                "Extract 1-2 sentence description from Workplan"
                "Do NOT add detailed checklists"
                "Do NOT add acceptance criteria"
                "Do NOT add implementation steps"
                "Do NOT add code examples"
            "Add next step prompt"
                "Tell user to run PLAN command"
                "Example: $ claude \"Выполни команду PLAN\""

        "Step 3: Update Workplan"
            "Find selected task"
                "Locate task by ID in Workplan.md"
            "Mark as in progress"
                "Add **INPROGRESS** marker to task row"
            "Save changes"
                "Write updated Workplan.md"

    "Outputs"
        "DOCS/INPROGRESS/next.md"
            "Contains minimal task metadata only"
            "Guides user to run PLAN for details"
        "DOCS/Workplan.md"
            "Updated with INPROGRESS marker"

    "Separation of Concerns"
        "SELECT responsibility"
            "Identify which task to work on next"
            "Create minimal task metadata file"
            "Update progress tracking"
        "PLAN responsibility"
            "Generate detailed implementation plan (PRD)"
            "Create acceptance criteria"
            "Define step-by-step checklist"
            "Provide code templates and examples"
        "EXECUTE responsibility"
            "Perform the actual implementation work"
            "Validate against acceptance criteria"
            "Update documentation and commit"

    "Error Handling"
        "No available tasks"
            "Exit with error message"
            "Suggest user reviews Workplan for blockers"
        "Multiple P0 tasks with equal priority"
            "Select first task on critical path"
            "Log decision rationale"
        "Parallel track tie"
            "Default to Track A preference"
            "Document tie-breaking logic"
