# SELECT Command Algorithm for CI in Hypercode
# Version: 1.1.0
# Purpose: Select next CI task from workplan based on priorities and dependencies

"SELECT — Next CI Task Selection"
    "Version: 1.1.0"

    "Purpose"
        "SELECT identifies the next CI task to work on based on priorities, dependencies, and phase order."
        "It does NOT create implementation plans - that's the job of the PLAN command."

    "Inputs"
        "DOCS/CI/Workplan.md"
            "Contains all CI tasks with priorities and dependencies"
        "DOCS/CI/INPROGRESS/next.md"
            "Current CI task being worked on"

    "Algorithm"
        "Step 1: Find Candidate Tasks"
            "Filter tasks by status"
                "Task must not be completed (checkbox is [ ] not [x])"
            "Check dependencies"
                "All dependent tasks must be completed"
                "Read Dependencies column from task table"
                "Verify each dependency is marked COMPLETE in Workplan"
            "Apply priority ordering"
                "High priority tasks: CI-01, CI-02, CI-03, CI-05, CI-07, CI-08, CI-10"
                "Medium priority tasks: CI-04, CI-06, CI-09"
            "Apply phase ordering"
                "Phase 1: Discovery (CI-01)"
                "Phase 2: Workflow Skeleton (CI-02, CI-03, CI-07)"
                "Phase 3: Quality Gates (CI-04, CI-05, CI-06)"
                "Phase 4: Validation & Docs (CI-08, CI-09, CI-10)"
            "Break ties"
                "Within same priority, prefer earlier phase"
                "Within same phase, prefer dependency chain order"
                "Within same chain, use task ID sequence (CI-01 → CI-02 → CI-03...)"

        "Step 2: Create Minimal next.md"
            "Write task header"
                "Format: # Next Task: {TASK_ID} — {TASK_NAME}"
            "Add basic metadata"
                "Priority: High/Medium"
                "Phase: {Phase Name}"
                "Effort: {Hours}"
                "Dependencies: {Task IDs or None}"
                "Status: Selected"
            "Add brief description"
                "Extract 1-2 sentence description from Workplan task column"
                "Do NOT add detailed checklists"
                "Do NOT add acceptance criteria"
                "Do NOT add implementation steps"
                "Do NOT add YAML examples"
            "Add next step prompt"
                "Tell user to run PLAN command for CI"
                "Example: $ claude \"Выполни команду PLAN для CI\""

        "Step 3: Update Workplan"
            "Find selected task"
                "Locate task by ID in Workplan table"
            "Mark as in progress"
                "Add **INPROGRESS** marker to Owner column"
            "Save changes"
                "Write updated DOCS/CI/Workplan.md"

    "Outputs"
        "DOCS/CI/INPROGRESS/next.md"
            "Contains minimal task metadata only"
            "Guides user to run PLAN for details"
        "DOCS/CI/Workplan.md"
            "Updated with INPROGRESS marker"

    "CI-Specific Priority Rules"
        "Critical path preference"
            "CI-01 → CI-02 → CI-03 → CI-05 → CI-10"
            "This path covers core functionality"
        "Parallel opportunities"
            "After CI-02: both CI-03 and CI-07 can proceed"
            "After CI-03: both CI-04 and CI-05 can proceed"
            "Prefer critical path (CI-03 over CI-07, CI-05 over CI-04)"

    "Separation of Concerns"
        "SELECT responsibility"
            "Identify which CI task to work on next"
            "Create minimal task metadata file"
            "Update progress tracking"
        "PLAN responsibility"
            "Generate detailed implementation plan (PRD)"
            "Create acceptance criteria"
            "Define step-by-step checklist"
            "Provide GitHub Actions YAML examples"
        "EXECUTE responsibility"
            "Implement the CI configuration"
            "Validate YAML syntax"
            "Test workflow triggers"
            "Update documentation and commit"

    "Error Handling"
        "No available tasks"
            "Exit with error message"
            "Suggest user reviews CI Workplan for blockers"
        "Multiple High priority tasks with dependencies satisfied"
            "Select first based on phase order"
            "Log decision rationale"
        "Parallel opportunities detected"
            "Prefer critical path (CI-01 → CI-02 → CI-03 → CI-05 → CI-10)"
            "Document parallel task alternatives"
