"Medium Project Fixture"
    "Overview"
        "Purpose: PRD medium benchmark"
        "Scope: 20 Hypercode files"
    "Structure"
        "Include depth target: 6"
    "section_01.hc"
    "section_02.hc"
    "section_03.hc"
    "section_04.hc"
    "section_13.hc"
    "section_15.hc"
    "section_17.hc"
    "section_19.hc"
    "notes_01.md"
    "notes_05.md"
