"Section 03 - Validation"
    "Targets"
        "Deterministic output"
        "Strict mode OK"
    "Signals"
        "Diagnostics"
        "Stats"
    "section_09.hc"
    "section_10.hc"
    "section_14.hc"
