"Section 02 - Pipeline"
    "Objectives"
        "Normalize inputs"
        "Track sources"
    "Checklist"
        "Parse"
        "Resolve"
        "Emit"
    "section_07.hc"
    "section_08.hc"
    "notes_03.md"
